### PR TITLE
Upgrade to d3 4.5

### PR DESCRIPTION
**Pull request by edwindj**
First of all, thanks for your wonderful component!

In a shiny dashboard that also used another d3 htmlwidget, the current chorddiag fails due to a clash of d3 versions (d3v3 vs d34.5). 

I have updated your widget to d3 version 4.5, by updating the components (d3 and d3-tip) and making minimal changes to your original code. (a more clean solution probably would be to redevelop the code from start to d3v4.5).
However everything seems to work fine, so you may be interested in this solution.

Best,

Edwin

### CODE REVIEW

**Comment by mattflor** [comment]
Hi Edwin,

Thanks a lot for your patches! I'm on vacation right now but will have a
look as soon as I'm back home.

Cheers, Matt


Edwin de Jonge <notifications@github.com> schrieb am Mi., 1. Aug. 2018,
23:37:

**Comment by strboul** [comment]
This contribution looks huge but I have never seen such a single long commit (that's also very odd to me) that can easily be merged. I'll keep an eye on this PR as it looks interesting.

**Comment by edwindj** [comment]
The  contribution looks larger than it is: I have updated the accompagnying javascript libraries (d3.js etc.). 
The real contribution are the (minor) changes to chorddiag.js.

**Comment by mattflor** [comment]
Sorry this took forever but I finally merged your pull request (actually updated d3 to v4.13.0 in the process). Just to let you know: I've added you as a contributor in the DESCRIPTION file, @edwindj. Thanks!

**Comment by edwindj** [comment]
Thanks! (And I know how it is to maintain R packages... :-) )

**Pull request merged**
